server:
  port: 9998
  tomcat:
    threads:
      max: 5
      min-spare: 3
    connection-timeout: 3000
spring:
  application:
    name: b2c-dubbo-server
dubbo:
  application:
    name: b2c-dubbo-server
    logger: slf4j
  registry:
    address: zookeeper://192.168.240.3:2181?timeout=30000
  protocol:
    name: dubbo
    port: 21899
    accesslog: true
    threads: 5
  scan:
    basePackages: org.javamaster.b2c