spring:
  application:
    name: b2c-cloud-test-boot
  profiles:
    active: ${active.profile.name}
  thymeleaf:
    cache: false
eureka:
  instance:
    hostname: eureka.dev.javamaster.com
    port: 8761
    nonSecurePort: ${server.port:8080}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
server:
  port: 8100
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /actua
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}