spring:
  application:
    name: b2c-cloud-test-config-git
  cloud.config.server:
    git:
      #脱离git服务器直接读取本地文件系统配置信息
      uri: file://D:/b2c-config-center
      #uri: https://github.com/jufeng98/b2c-config-center.git
      searchPaths: /general,/common
      username: jufeng98
      password: '******'
      repos:
        configSec:
          pattern: doc/*
          cloneOnStart: true
          uri: file://D:/b2c-config-center-sec
          #uri: https://github.com/jufeng98/b2c-config-center-sec.git
          searchPaths: /javamaster
          username: jufeng98
          password: '******'
    health.enabled: false
server:
  port: 9101
eureka:
  instance:
    hostname: eureka.dev.javamaster.com
    port: 8761
    nonSecurePort: ${server.port}
    preferIpAddress: true
    statusPageUrlPath: /info
    #healthCheckUrlPath: ${server.context-path}/health    
  client:
    #服务缓存清单的更新时间,默认为30s
    registryFetchIntervalSeconds: 10
    registerWithEureka: true
    fetchRegistry: true      
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false
endpoints: 
  shutdown: 
    enabled: true          
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
  my-plugin-pachagetime: ${plugin.pachagetime}