spring:
  application:
    name: b2c-cloud-test-redis
eureka:
  instance:
    hostname: eureka.dev.javamaster.com
    port: 8761
    nonSecurePort: ${server.port:8600}
    preferIpAddress: true
    statusPageUrlPath: /info
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false
server:
  port: 8600
endpoints:
  shutdown:
    enabled: true
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
  ip: ${spring.cloud.client.ipAddress}
  env: ${active.profile.name}
  system: ${os.name}