spring:
  application:
    name: b2c-cloud-test-pattern
  session: 
    store-type: none
eureka:
  instance:
    hostname: localhost
    port: 8761
    nonSecurePort: ${server.port:8080}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
server:
  port: 8886
management:
  security:
    enabled: false
info:
  service-name: ${spring.application.name}
  ip: ${spring.cloud.client.ipAddress}