spring:
  application:
    name: b2c-cloud-test-user
server:
  port: 8999
eureka:
  instance:
    hostname: 127.0.0.1
    port: 8761
    nonSecurePort: ${server.port:8600}
    preferIpAddress: true
    statusPageUrlPath: /info
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  server:
    servlet:
      context-path: /actuator
      security:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
  ip: ${spring.cloud.client.ip-address}
  env: ${active.profile.name}
  system: '@os.name@'