spring:
  application:
    name: b2c-cloud-test-hystrix
  profiles:
    active: ${active.profile.name}
server:
  port: 8400
eureka:
  instance:
    hostname: eureka.dev.javamaster.com
    port: 8761
    leaseExpirationDurationInSeconds: 10000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}