spring:
  application:
    name: b2c-cloud-test-security
  datasource:
    url: jdbc:h2:file:~/h2/testdb
    username: sa
    password: sa
logging:
  level:
    org:
      hibernate: debug
eureka:
  instance:
    hostname: eureka.dev.javamaster.com
    port: 8761
    nonSecurePort: ${server.port:8080}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  context-path: /actuator
  security:
    enabled: false
server:
  port: 8600
  context-path: /security