eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: b2c-admin
server:
  port: 8259
management:
  endpoints:
    web:
      exposure:
        include: '*'